# Generated by Django 5.0.3 on 2024-06-11 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('matricula', models.CharField(default='', max_length=15)),
                ('turma', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credetinals', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('image', models.CharField(default='a', max_length=200)),
                ('alunos', models.ManyToManyField(related_name='grupos', to='feedbackApp.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sharedToProfessor', models.ManyToManyField(related_name='professoresAdmins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Status Report 1', max_length=255)),
                ('pensamento_critico_criatividade', models.FloatField(verbose_name='Pensamento Crítico e Criatividade')),
                ('comunicacao', models.FloatField(verbose_name='Comunicação')),
                ('colaboracao', models.FloatField(verbose_name='Colaboração')),
                ('qualidade_entregas', models.FloatField(verbose_name='Qualidade das Entregas')),
                ('presenca', models.FloatField(verbose_name='Presença')),
                ('entrega_prazos', models.FloatField(verbose_name='Entrega e Prazos')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.aluno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.grupo')),
            ],
        ),
    ]
