# Generated by Django 5.0.3 on 2024-06-07 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0002_remove_aluno_colaboracao_remove_aluno_comunicacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='sharedToProfessor',
            field=models.ManyToManyField(related_name='professoresAdmins', to=settings.AUTH_USER_MODEL),
        ),
    ]
