# Generated by Django 5.0.3 on 2024-06-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0003_grupo_sharedtoprofessor'),
        ('feedbackApp', '0004_alter_aluno_email'),
    ]

    operations = [
    ]
