# Generated by Django 5.0.3 on 2024-06-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0006_googlecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='image',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
